project:
  type: website
  output-dir: docs

website:
  title: "witch-tutorial"
  site-url: https://witch-team.github.io/witch-tutorial/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

